### ISSUE TITLE
Crash: Playing Find Familiar

### ISSUE THREAD

**Issue by mdiehr** [dbjorge/jorbs-spire-mod#10]
Looks like a language/localization issue.

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at stsjorbsmod.powers.FindFamiliarPower.updateDescription(FindFamiliarPower.java:50) ~[JorbsMod.jar:?]
	at stsjorbsmod.powers.FindFamiliarPower.<init>(FindFamiliarPower.java:38) ~[JorbsMod.jar:?]
	at stsjorbsmod.cards.FindFamiliar.use(FindFamiliar.java:30) ~[JorbsMod.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1676) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:347) ~[?:?]
```

**Comment by mdiehr** [comment]
Line in question:
`        description = DESCRIPTIONS[0] + this.amount + DESCRIPTIONS[1];`
