### ISSUE TITLE
Game crashes after bandits event (Bug)

### ISSUE THREAD

**Issue by GwathEledh** [dbjorge/jorbs-spire-mod#141]
With Version 0.34.1
After a combat with Temperance the game crashed when I chose to pay the bandits (Act 2 event).

**Comment by wang429** [comment]
```
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.monsters.AbstractMonster.applyPowers(AbstractMonster.java:1326) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.onModifyPower(AbstractDungeon.java:3173) ~[?:?]
	at stsjorbsmod.patches.OnModifyGoldPatch.notifyModifyGold(OnModifyGoldPatch.java:25) ~[JorbsMod.jar:?]
	at stsjorbsmod.patches.OnModifyGoldPatch.access$000(OnModifyGoldPatch.java:12) ~[JorbsMod.jar:?]
	at stsjorbsmod.patches.OnModifyGoldPatch$AbstractPlayer_loseGold.patch(OnModifyGoldPatch.java:50) ~[JorbsMod.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.loseGold(AbstractPlayer.java:827) ~[?:?]
	at com.megacrit.cardcrawl.events.city.MaskedBandits.buttonEffect(MaskedBandits.java:60) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.events.AbstractEvent.update(AbstractEvent.java:124) ~[?:?]
	at com.megacrit.cardcrawl.events.city.MaskedBandits.update(MaskedBandits.java:46) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.update(EventRoom.java:30) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2494) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:871) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:422) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

```

**Comment by wang429** [comment]
Seems like the issue is fairly specific to Masked Bandits (Beggar, Addict, and World of Goop don't seem to trigger this. The remembered memory didn't matter - Diligence also caused the situation. The important thing is having *no* powers at the end of combat.

Steps to reproduce:
End a fight with no powers
Enter Masked Bandits event
Lose all gold
Crash.
